image: alpine/edge
packages:
  - go
  - curl
sources:
  - https://git.sr.ht/~bouncepaw/betula
tasks:
  - test-go: |
      cd betula
      go test ./db
      go test ./feeds
  - test-web: |
      cd betula
      sh test-web.sh
      killall betula
